# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-03 22:14
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import messaging.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Please keep the message interesting <3', validators=[django.core.validators.MinLengthValidator(200, message='Messages need at least 200 chars'), django.core.validators.MaxLengthValidator(400, message='Messages need to be under 400 chars')])),
                ('worker', models.CharField(choices=[('BASIC', 'Mail pigeon'), ('HARDY', 'Guerrilla pigeon'), ('EMU', 'Ausie pigeon'), ('SUSHI', 'Sushi pigeon')], default=messaging.models.random_worker_type, help_text='Kind of pigeon worker that will deliver message', max_length=5)),
                ('sent_date', models.DateTimeField(auto_now=True, help_text='When the message was sent')),
                ('seed', models.PositiveIntegerField(default=messaging.models.generate_seed, help_text='Seed to use when generating events')),
                ('events_seen', models.PositiveIntegerField(default=0, editable=False, help_text='Amount of events that sender has seen')),
                ('receiver', models.ForeignKey(help_text='User who should receive the message', on_delete=django.db.models.deletion.CASCADE, related_name='receivers', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(help_text='User who sent the message', on_delete=django.db.models.deletion.CASCADE, related_name='senders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
